// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXpI7wcKDVrknYrCrpRW3NKbDFhwBHAxY',
    appId: '1:942554870984:web:562d1682d7c75ad132a1fd',
    messagingSenderId: '942554870984',
    projectId: 'ecommerce-app-12c8c',
    authDomain: 'ecommerce-app-12c8c.firebaseapp.com',
    storageBucket: 'ecommerce-app-12c8c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-CYlLDQuw70ySLZuvBHK9yJhr_BKY7uQ',
    appId: '1:942554870984:android:244a8f7a8ca2d7fc32a1fd',
    messagingSenderId: '942554870984',
    projectId: 'ecommerce-app-12c8c',
    storageBucket: 'ecommerce-app-12c8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD35LGMaJQWdUTLlyAXoozsvIA6yv5Oz1c',
    appId: '1:942554870984:ios:2a183ffe2547c0c332a1fd',
    messagingSenderId: '942554870984',
    projectId: 'ecommerce-app-12c8c',
    storageBucket: 'ecommerce-app-12c8c.firebasestorage.app',
    androidClientId: '942554870984-8g7f9r60prk8onc8rsgtp29680mo0gm8.apps.googleusercontent.com',
    iosClientId: '942554870984-aeb9q19mmpckr7sv1nhue2emfep35f1i.apps.googleusercontent.com',
    iosBundleId: 'com.codingwitht.ecommerce.tstoreEcommerceApp',
  );

}